[package]
name = "compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
syntax = { path = "../syntax" }
evaluator = { path = "../evaluator" }
ir = { path = "../IR" }
Arm64Backend = { path = "../Arm64Backend"}